### ISSUE TITLE
Isn't the placement of Dockerfiles here bad for CD and security?

### ISSUE THREAD

**Issue by cusspvz** [rancher/compose-templates#3]
Software is always evolving, thats why _SemVer_ is adopted almost everywhere, including on mostly _docker images_. As so, my question are:

Why are you placing images `Dockerfile` and respective assets?
Are them maintained on this repo?
Is `docker-compose.yml`, despite their image info, building from those?

Thanks :)

**Comment by cloudnautique** [comment]
@cusspvz, thanks for asking these questions. The purpose of this repo is to publish app templates that work with Rancher so that we know we have built the needed tooling for our users to run complex apps. The second reason is  it gives our users an easy starting point to launch these applications and to see how to build applications on their own. We make it a point to pin our dependencies where we can so that we get reproducible builds. The compose files use versioned images for reproducibility. Our envvars and configurations are minimal to get up and running. We expect things to be adjusted to each users environment. To help with that we are trying to use Confd which can read from many backends (Rancher metadata, etcd, consul etc) so that its a simple change to get config values from someplace else. You could also completely replace our sidekick config containers with your own. 

Why are you placing images Dockerfile and respective assets? 
  We are building and pushing versioned images when updated to the Rancher org on Dockerhub. Users often want to see how these images are built, or want to build them on their own. So we put the files here to keep it simple. Where possible, we use the plain vanilla official Dockerhub repos and just inject what we need through side kicks. 

Are they maintained on this repo?
  We are doing all of our work here, and will be updating as we fix issues and add applications. 

Is docker-compose.yml, despite their image info, building from those?
 That would be a good feature :) we do not use the build feature on Rancher compose to build these. The compose files assume you have built the images locally or pushed them to a registry. 

The flow we sort of envision for this is...
- User clones the repo
- Optionally builds the images and pushes to their registry.
- Modifies the compose / rancher yaml files with runtime configurations.
- Commits it to their fork. 
- Users CI system
- Users CD system

Periodically, I could see users bringing over stuff from this repo again around upgrades and such.

**Comment by cusspvz** [comment]
Thanks for replying with lots of info! :)

> The purpose of this repo is to publish app templates that work with Rancher so that we know we have built the needed tooling for our users to run complex apps. 

Thats awesome! I think it is just the major thing missing on Rancher, inspite I've already expressed that. :+1: 

> The second reason is it gives our users an easy starting point to launch these applications and to see how to build applications on their own

If I had option to vote on that, I would choose kind of `service-boilerplate` or individual example repos for each kind of service discovery gathering (such as confd, using `dig`, fetching `metadata` and so on) instead of mixing them all. Also there are some stacks that are way to complex to deploy, since they have different deploy approaches and depend on the user software arch, language using and so on.

> We are building and pushing versioned images when updated to the Rancher org on Dockerhub. Users often want to see how these images are built, or want to build them on their own. So we put the files here to keep it simple. Where possible, we use the plain vanilla official Dockerhub repos and just inject what we need through side kicks.
> 
> We are doing all of our work here, and will be updating as we fix issues and add applications.

Wouldn't be easy to create a separated org on Github (like `rancher-stacks`) with each one as individual repo?
It would be easier to maintain and track fixes/updates, this repo would be sort of templates `index` gathering for the UI/Compose.

> That would be a good feature :) we do not use the build feature on Rancher compose to build these. The compose files assume you have built the images locally or pushed them to a registry.

Honestly I agree if its for test proposes such as CI test builds. I don't see as a feature for development, imagine that you have the 'production' environment keys loaded on shell and execute `rancher-compose build` accidentally, you would see your production going down piece by piece... hahaha

---

Resuming, IMHO, its important to divide your _stacks_ configuration from images sources.

Don't know if I can propose such a thing, but, what do you think about:
- Creation of a org on GitHub (like `rancher-services`):
  - Would be the home for rancher services images.
  - LB and NA could be moved here.
  - All other services that rancher supports officially or supported by the rancher community could also be here, stuff such as: mysql, redis, mongo, couchdb and all other kind of most used images that are already compatible with rancher discovery.
- Alter the structure of this repo for something like:
  - stack-name/ <- folder with stack name
    - stack.yml <- yml with info such as: name, description, environment variables and their specs (name, type, validation, description) and other stuff thats not crossing my mind right now.
    - docker-compose.yml.tpl <- docker-compatible compose template, where it has variable placeholders
    - README.md <- Some stacks could have different configuration patterns, as so, its useful to have some kind of docs

Tell me what do you think about this idea, anyway I think I will PR some services to here on the next few days.

**Comment by cloudnautique** [comment]
Thanks for the discussion! These are a first pass at launching the apps, and we are working towards the app catalogue feature. The format will be changing to accommodate the new service. It is very similar to the format your describing.

I think we merged rancher-compose variable substitution to match docker-compose behavior.

Thanks for the feedback!

**Comment by cloudnautique** [comment]
Closing this now that we have catalog available.
